Repository evolutio/djavue3, pull requests merged in 2023-10, with the labels that each got.

#48 Melhora a geração do .env e pergunta inicial para usar docker/virtualenv
  cookiecutter.json
  hooks/post_gen_project.py
  {{cookiecutter.project_slug}}/.env
  {{cookiecutter.project_slug}}/docker-compose.yml
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/base/templates/base/apihome.html
Labels: HACKTOBERFEST

#49 issue#47 - Adiciona rota /status e test_status.py
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/base/tests.py
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/base/tests/test_status.py
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/base/urls.py
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/base/views.py
Labels: backend, HACKTOBERFEST

#52 Melhora a vida de quem esta querendo subir tudo sem docker. Issue #50
  {{cookiecutter.project_slug}}/.env
  {{cookiecutter.project_slug}}/frontend/.env
  {{cookiecutter.project_slug}}/requirements-dev.txt
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/accounts/views.py
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/{{cookiecutter.app_name}}/views.py
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#56 Adiciona versão inicial da documentação em 🇬🇧 Inglês. Issue #55
  docs/.vitepress/config.mjs
  docs/README_EN.md
  docs/images/local-env-using-docker.jpg
  docs/images/local-env-without-docker.jpg
  docs/images/local-run-without-docker-localhost-3000.jpg
  docs/images/local-run-without-docker-localhost-8000.jpg
Labels: documentation, HACKTOBERFEST

#58 Update front libs (vue, vuetify, pinia, vite). Issue #54
  {{cookiecutter.project_slug}}/frontend/.env
  {{cookiecutter.project_slug}}/frontend/package-lock.json
  {{cookiecutter.project_slug}}/frontend/package.json
Labels: HACKTOBERFEST

#61 Issue60 poetry
  README.md
  docs/README_EN.md
  hooks/post_gen_project.py
  {{cookiecutter.project_slug}}/.github/workflows/python-app-ci.yml
  {{cookiecutter.project_slug}}/.gitignore
  {{cookiecutter.project_slug}}/pyproject.toml
Labels: HACKTOBERFEST
