Repository evolutio/djavue3, pull requests merged in 2024-10, with the labels that each got.

#98 Issue #97 🧹 Remove arquivos não utilizados
  {{cookiecutter.project_slug}}/.gitlab-ci.yml
  {{cookiecutter.project_slug}}/docker-compose.apimock.yml
  {{cookiecutter.project_slug}}/docker/bin/start.sh
  {{cookiecutter.project_slug}}/docker/bin/start_dev.sh
  {{cookiecutter.project_slug}}/docker/bin/start_front.sh
  {{cookiecutter.project_slug}}/docker/bin/start_web.sh
  {{cookiecutter.project_slug}}/docker/bin/stop_web.sh
  {{cookiecutter.project_slug}}/uwsgi.ini
Labels: enhancement, HACKTOBERFEST

#96 Issue 80. Remove a opção da API com openapi.
  cookiecutter.json
  docs/02-iniciando.md
  docs/README_EN.md
  hooks/post_gen_project.py
  {{cookiecutter.project_slug}}/pyproject.toml
  {{cookiecutter.project_slug}}/requirements-dev-txt-openapi.pip
  {{cookiecutter.project_slug}}/requirements.txt
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/base/templates/base/apidocs.html
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/base/urls.py
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/base/views.py
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/connexion.py
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/openapi.yaml
  {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/urls.py
Labels: enhancement, HACKTOBERFEST

#101 Issue 97. KISS. Remove license para fica mais simples
  LICENSE
  cookiecutter.json
  docs/02-iniciando.md
  docs/README_EN.md
  {{cookiecutter.project_slug}}/pyproject.toml
Labels: DX, HACKTOBERFEST

#100 Issue #99. KISS Remove pip-tools das opções de setup do projeto
  cookiecutter.json
  docs/05-gerenc-pacotes.md
  docs/README_EN.md
  hooks/post_gen_project.py
  {{cookiecutter.project_slug}}/Dockerfile
  {{cookiecutter.project_slug}}/requirements-dev-txt-django_ninja.pip
  {{cookiecutter.project_slug}}/requirements-dev-txt-django_only.pip
  {{cookiecutter.project_slug}}/requirements-dev.txt
Labels: HACKTOBERFEST

#105 Ajuste nas versões utilizando operadores ^ e ~. Issue #53
  {{cookiecutter.project_slug}}/pyproject.toml
Labels: HACKTOBERFEST

#110 feat: added english docs
  docs/.gitignore
  docs/.vitepress/cache/deps/@theme_index.js
  docs/.vitepress/cache/deps/_metadata.json
  docs/.vitepress/config.mjs
  docs/en/01-o-que-eh.md
  docs/en/02-iniciando.md
  docs/en/03-sem-docker.md
  docs/en/04-com-docker.md
  docs/en/05-gerenc-pacotes.md
  docs/en/06-organizacao.md
  docs/en/07-debug.md
  docs/en/08-api-mock.md
  docs/en/09-deploy.md
  docs/en/10-CI-e-CD.md
  docs/en/11-contribuindo.md
  docs/en/changelog.md
  docs/en/index.md
  docs/package-lock.json
Labels: documentation, HACKTOBERFEST

#113 Feat/translating organization to en
  docs/.vitepress/config.mjs
  docs/06-organizacao.md
  docs/README_EN.md
  docs/en/06-organizacao.md
Labels: enhancement, HACKTOBERFEST

#115 chore: set cookiecutter human readable prompts
  cookiecutter.json
Labels: documentation, enhancement, HACKTOBERFEST

#123 Prompt melhor sem perguntar várias vezes o nome do model
  cookiecutter.json
  hooks/pre_gen_project.py
Labels: DX, HACKTOBERFEST
